version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: imf-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9423635767
      POSTGRES_DB: imf_gadgets
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  imf-api:
    build: .
    container_name: imf-gadget-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/imf_gadgets
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 9423635767
    ports:
      - "8080:8080"

volumes:
  pgdata:
